### PR TITLE
Shrink images and mimify generated JSON

### PR DESCRIPTION
**Pull request by absidue**

### CODE REVIEW

**Comment by Shugabuga** [comment]
Is there a reason this was closed?

**Comment by absidue** [comment]
I closed it due to inactivity

**Comment by absidue** [comment]
I can reopen it if you would like me to?

**Comment by Shugabuga** [comment]
Oh, ok. I'll reopen it since I may want to merge it later (when I have the chance to look over it).

**Comment by Shugabuga** [comment]
Just got around to reviewing this and also did some preliminary tests. I like it!

Merging.

**Pull request merged**
